services:
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin1
      restart: always
      ports:
        - 5050:80
      env_file:
        - ./.env
  postgres_db:
    image: postgres:14.15
    container_name: postgres_db
    restart: always
    ports:
      - "5440:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
volumes:
  postgres_db_data: